<?php

namespace AppBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTicketByDay($dateDeVisite)
    {
        return $this->createQueryBuilder('t')
            ->innerJoin('t.commande', 'commande')
            ->addSelect('commande')
            ->where('commande.dateDeVisite = :date')
            ->setParameter('date', $dateDeVisite)
            ->getQuery()
            ->getResult();
    }

}
