louvre_home:
    path:   /
    defaults: { _controller: AppBundle:Louvre:home}
    methods:  [GET]

louvre_commande:
    path:   /commande
    defaults: { _controller: AppBundle:Louvre:commande}
    methods:  [GET, POST]

louvre_ticket:
    path:   /commande/ticket
    defaults: { _controller: AppBundle:Louvre:ticket}
    methods:  [GET, POST]

louvre_checkout:
    path:    /commande/checkout
    defaults: { _controller: AppBundle:Louvre:checkout}
    methods:  [POST]

louvre_informations:
    path:    /informations
    defaults: { _controller: AppBundle:Louvre:informations}
    methods:  [GET]

louvre_help:
    path:    /aide
    defaults: { _controller: AppBundle:Louvre:help}
    methods:  [GET]

louvre_searchorder:
    path:    /recuperationdecommande
    defaults: { _controller: AppBundle:Louvre:searchorder}
    methods:  [GET, POST]

louvre_confirmation:
    path:   /commande/confirmation
    defaults: { _controller: AppBundle:Louvre:confirmation}
    methods:  [GET]

louvre_prepare:
    path:   /commande/prepare
    defaults: { _controller: AppBundle:Louvre:prepare}
    methods:  [GET]

louvre_foundorder:
    path:   /commanderecuperee
    defaults: { _controller: AppBundle:Louvre:foundorder}
    methods:  [GET]



