louvre_accueil:
    path:   /
    defaults: { _controller: AppBundle:Louvre:accueil}

louvre_commande:
    path:   /commande
    defaults: { _controller: AppBundle:Louvre:commande}

louvre_ticket:
    path:   /commande/ticket
    defaults: { _controller: AppBundle:Louvre:ticket}

louvre_confirmation:
    path:   /commande/confirmation
    defaults: { _controller: AppBundle:Louvre:confirmation}

louvre_checkout:
    path:    /commande/checkout
    defaults: { _controller: AppBundle:Louvre:checkout}

louvre_informations:
    path:    /informations
    defaults: { _controller: AppBundle:Louvre:informations}

louvre_aide:
    path:    /aide
    defaults: { _controller: AppBundle:Louvre:aide}

louvre_retrieve:
    path:    /recuperationdecommande
    defaults: { _controller: AppBundle:Louvre:retrieve}