louvre_home:
    path:   /
    defaults: { _controller: AppBundle:Louvre:home}

louvre_commande:
    path:   /commande
    defaults: { _controller: AppBundle:Louvre:commande}

louvre_ticket:
    path:   /commande/ticket
    defaults: { _controller: AppBundle:Louvre:ticket}

louvre_confirmation:
    path:   /commande/confirmation
    defaults: { _controller: AppBundle:Louvre:confirmation}

louvre_checkout:
    path:    /commande/checkout
    defaults: { _controller: AppBundle:Louvre:checkout}

louvre_informations:
    path:    /informations
    defaults: { _controller: AppBundle:Louvre:informations}

louvre_help:
    path:    /aide
    defaults: { _controller: AppBundle:Louvre:help}

louvre_retrieve:
    path:    /recuperationdecommande
    defaults: { _controller: AppBundle:Louvre:retrieve}