louvre_accueil:
    path:   /
    defaults: { _controller: AppBundle:Louvre:accueil}

louvre_commande:
    path:   /commande
    defaults: { _controller: AppBundle:Louvre:commande}

louvre_ticket:
    path:   /commande/ticket
    defaults: { _controller: AppBundle:Louvre:ticket}

louvre_confirmation:
    path:   /commande/confirmation
    defaults: { _controller: AppBundle:Louvre:confirmation}

louvre_prepare:
    path:   /commande/prepare
    defaults: { _controller: AppBundle:Louvre:prepare}

louvre_checkout:
    path:    /commande/checkout
    defaults: { _controller: AppBundle:Louvre:checkout}