# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.limitPerDay:
            class: AppBundle\Service\LimitPerDay
            arguments:
                        - '@doctrine.orm.entity_manager'
    app.price:
            class: AppBundle\Service\Price

    app.stripe:
            class: AppBundle\Service\Stripe
            arguments: ['%skapikey%']

    app.verifOrder:
            class: AppBundle\Service\VerifOrder
